### ISSUE TITLE
MultiValueDictKeyError

### ISSUE THREAD

**Issue by shopkueche** [morlandi/django-ajax-datatable#106]
Hello,
I tried to implement django-ajax-datatable to my existing project. If I implement the example-project from the readme-file I will get an key error.
(https://github.com/morlandi/django-ajax-datatable#14basic-ajaxdatatableview)

Does somebody had the same issue and know how to fix this? 

MultiValueDictKeyError at /ajax_datatable/permissions/
'draw'
Request Method:	GET
Request URL:	http://127.0.0.1:8004/ajax_datatable/permissions/
Django Version:	4.1.7
Exception Type:	MultiValueDictKeyError
Exception Value:	
'draw'

**Comment by idoziru** [comment]
@shopkueche hi! Did you find how to fix it?

**Comment by idoziru** [comment]
@morlandi hi. Great thanks for your work. Maybe you know how it is possible to resolve the same issue? 

`Environment:


Request Method: GET
Request URL: https://arcadia.investgame.net/db/deals/

Django Version: 4.1.7
Python Version: 3.11.2
Installed Applications:
['django_light',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'arcadia',
 'apps.devops',
 'apps.users',
 'apps.utils',
 'apps.db',
 'apps.taxonomy',
 'ajax_datatable']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)

During handling of the above exception ('draw'), another exception occurred:
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/ajax_datatable/views.py", line 411, in dispatch
    response = super(AjaxDatatableView, self).dispatch(request, *args, **kwargs)
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/ajax_datatable/views.py", line 534, in get
    params = self.read_parameters(query_dict)
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/ajax_datatable/views.py", line 587, in read_parameters
    params = {field: int(query_dict[field]) for field in ['draw', 'start', 'length']}
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/ajax_datatable/views.py", line 587, in <dictcomp>
    params = {field: int(query_dict[field]) for field in ['draw', 'start', 'length']}
  File "/home/web/.pyenv/versions/3.11.2/envs/arcadia/lib/python3.11/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)

Exception Type: MultiValueDictKeyError at /db/deals/
Exception Value: 'draw'
`

**Comment by idoziru** [comment]
My mistake. Didn't read the documentation carefully. We need two views. For table presentation and for AJAX.

**Comment by pomara-photys** [comment]
Hi @idoziru , I am also experiencing the same error. Could you help explain what you did to resolve the issue?

**Comment by idoziru** [comment]
@pomara-photys, hello! 

I'd be happy to help. Like this:

I didn't read the documentation carefully. You need two views:
- A view for displaying the table.
- A view that will make an AJAX request, retrieve data, and insert it into the table.

The documentation provides a good example of all the views, templates, URL files, and so on. You can find it at this [link](https://github.com/morlandi/django-ajax-datatable/tree/master/example_minimal/example_minimal). Note, that there are two files: views.py and ajax_datatable_views.py.
